name: Update README with Language Chart

on:
  schedule:
    - cron: '0 0 * * 1' # Runs every Monday at 00:00 UTC
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate language chart
        uses: anuraghazra/github-readme-stats@master
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Update README
        run: |
          echo "## Most Used Languages" > languages.md
          echo "![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=AbanoubSeddik&layout=compact)" >> languages.md
          cat languages.md >> README.md
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m 'Update README with language chart'
          git push
